### PR TITLE
Removefiles

### PR DESCRIPTION
**Pull request by razgoth**
This is a new branch used to remove files

### CODE REVIEW

**Comment by platisd** [comment]
`git rebase master` and then `git push -f`

**Comment by platisd** [comment]
Or rather, `git checkout master`, `git pull --rebase`, `git checkout -`, `git rebase master` and finally `git push -f`

**Comment by platisd** [comment]
You don't have to close the pull request, just push new files to it! :)

**Comment by razgoth** [comment]
I took screen shots for everything I did, it ends up with “There isn’t anything to compare” maybe I misunderstood your instructions again

Or rather, git checkout master, git pull --rebase, git checkout -, git rebase master and finally git push -f

[cid:image001.png@01D62569.21DFB0B0]

[cid:image002.png@01D62569.21DFB0B0]

[cid:image003.png@01D62569.21DFB0B0]


[cid:image004.png@01D62569.21DFB0B0]

**Comment by platisd** [comment]
I cannot see the screen shots and they probably wouldn't say much. I guess you've put the local repo in a "strange" state. There are multiple ways to fix it and I'd suggest you look into them by trying things out and googling. It will eventually make you much more comfortable with git. And being comfortable with git is pretty much a self evident requirement in the industry.

To move forward create a fresh clone of the repository. Create a new branch. Remove the files you want and finally push to the new branch.

**Pull request closed without merging**
